name: Test and Publish Extension

on:
  push:
    branches:
      - main  
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: pip install poetry

    - name: Install Dependencies
      run: |
        cd dev_scripts
        poetry config virtualenvs.create false
        poetry install 

    - name: Run Acceptance Tests
      run: |
        cd dev_scripts
        poetry run pytest -k acceptance

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Package and Publish
      run: |
        npm install -g vsce
        vsce package
        vsce publish -p ${{ secrets.VS_MARKETPLACE_TOKEN }}
